[project]
name = "pylognet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.1",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "uvicorn>=0.38.0",
]
